// This file is generated by Sapper — do not edit it!
export const timestamp = 1610908243501;

export const files = [
	"service-worker-index.html",
	".DS_Store",
	"favicons/favicon-16x16.png",
	"favicons/favicon-32x32.png",
	"fonts/.DS_Store",
	"fonts/KapraNeue-Regular.otf",
	"global.css",
	"images/.DS_Store",
	"images/icons/.DS_Store",
	"images/icons/icon-192x192.png",
	"images/icons/icon-512x512.png",
	"images/logo/m30-logo.png",
	"images/motivators/.DS_Store",
	"images/motivators/de/acceptance.png",
	"images/motivators/de/curiosity.png",
	"images/motivators/de/freedom.png",
	"images/motivators/de/goal.png",
	"images/motivators/de/honor.png",
	"images/motivators/de/mastery.png",
	"images/motivators/de/order.png",
	"images/motivators/de/power.png",
	"images/motivators/de/relatedness.png",
	"images/motivators/de/status.png",
	"images/motivators/en/acceptance.png",
	"images/motivators/en/curiosity.png",
	"images/motivators/en/freedom.png",
	"images/motivators/en/goal.png",
	"images/motivators/en/honor.png",
	"images/motivators/en/mastery.png",
	"images/motivators/en/order.png",
	"images/motivators/en/power.png",
	"images/motivators/en/relatedness.png",
	"images/motivators/en/status.png",
	"images/motivators/es/acceptance.png",
	"images/motivators/es/curiosity.png",
	"images/motivators/es/freedom.png",
	"images/motivators/es/goal.png",
	"images/motivators/es/honor.png",
	"images/motivators/es/mastery.png",
	"images/motivators/es/order.png",
	"images/motivators/es/power.png",
	"images/motivators/es/relatedness.png",
	"images/motivators/es/status.png",
	"images/motivators/fr/.DS_Store",
	"images/motivators/fr/acceptance.png",
	"images/motivators/fr/curiosity.png",
	"images/motivators/fr/freedom.png",
	"images/motivators/fr/goal.png",
	"images/motivators/fr/honor.png",
	"images/motivators/fr/mastery.png",
	"images/motivators/fr/order.png",
	"images/motivators/fr/power.png",
	"images/motivators/fr/relatedness.png",
	"images/motivators/fr/status.png",
	"introduction.jpeg",
	"manifest.json"
];
export { files as assets }; // legacy

export const shell = [
	"client/client.230a3b95.js",
	"client/index.4b719fe5.js",
	"client/index.9f33858a.js",
	"client/sapper-dev-client.1e7a4a5e.js",
	"client/en.3e3a394e.js",
	"client/fr-FR.54a2bdd3.js",
	"client/client.9f7ba8c8.js"
];

export const routes = [
	{ pattern: /^\/$/ },
	{ pattern: /^\/about\/?$/ }
];