// This file is generated by Sapper — do not edit it!
export { default as Root } from '../../../routes/_layout.svelte';
export { preload as root_preload } from './shared';
export { default as ErrorComponent } from '../../../routes/_error.svelte';

export const ignore = [];

export const components = [
	{
		js: () => import("../../../routes/index.svelte"),
		css: "__SAPPER_CSS_PLACEHOLDER:index.svelte__"
	},
	{
		js: () => import("../../../routes/about/index.svelte"),
		css: "__SAPPER_CSS_PLACEHOLDER:about/index.svelte__"
	}
];

export const routes = [
	{
		// index.svelte
		pattern: /^\/$/,
		parts: [
			{ i: 0 }
		]
	},

	{
		// about/index.svelte
		pattern: /^\/about\/?$/,
		parts: [
			{ i: 1 }
		]
	}
];

if (typeof window !== 'undefined') {
	import("/Users/anthonylegoas/Dev/workspaces/perso/moving-motivators/node_modules/sapper/sapper-dev-client.js").then(client => {
		client.connect(10000);
	});
}