// This file is generated by Sapper — do not edit it!
import component_0 from "../../../routes/index.svelte";
import component_1 from "../../../routes/about/index.svelte";
import root from "../../../routes/_layout.svelte";
import error from "../../../routes/_error.svelte";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		
	],

	pages: [
		{
			// index.svelte
			pattern: /^\/$/,
			parts: [
				{ name: "index", file: "index.svelte", component: component_0 }
			]
		},

		{
			// about/index.svelte
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about/index.svelte", component: component_1 }
			]
		}
	],

	root,
	root_preload: () => {},
	error
};

export const build_dir = "__sapper__/dev";

export const src_dir = "src";

export const dev = true;